spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-backend
    password: admin
    username: postgres
    driveClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

  liquibase:
    changeLog: classpath:master.xml
    url: jdbc:postgresql://localhost:5432/taxi-backend
    user: postgres
    password: admin
